### PR TITLE
Add responsive iFrame mode, improve iFrame border

### PR DESCRIPTION
**Pull request by abias**
Hi,

I added a responsive iFrame mode and would like to ask you to pull the commit and publish the new version in the Moodle plugin repo.

Thanks,
Alex

### CODE REVIEW

**Comment by goldquest** [comment]
That's a nice idea.
Can we combine it with the vertical JavaScript YUI resizer?

**Comment by abias** [comment]
Hi Timo,

what would be the goal of using the YUI resizer?

The new reponsive mode will adapt the horizontal width to the view port, but will keep the (fixed 500px) height of the iframe - at least that was the case in my tests.

Thanks,
Alex

**Comment by goldquest** [comment]
The goal would be, that a user can make the editor bigger in terms of height (e.g. if he has a big monitor)

**Comment by abias** [comment]
I saw the code in your current implementation of the iframe, but did not adopt it up to now.

I will have a look at that next week. 
The main question is for me: Will YUI resize work on mobile devices?

**Comment by goldquest** [comment]
Hmm...
On mobile, In our version of etherpadlite, it just shows the whole content at once. So there would be no need of a resizer.
So for mobile, we could hide the resizer.
What do you think?

**Pull request merged**
