### PR TITLE
Smaller monologo icon for Moodle ≥ 4.4.

### PR DESCRIPTION
**Pull request by lucaboesch**
In Moodle 4.4, the icons become somewhat smaller, with whitespace around it.

### CODE REVIEW

**Comment by grabs** [comment]
Hi Luca, thanks for the request. It is now integrated to the main and MOODLE_404_STABLE branch. Note: the master branch now is obsolete but I can't delete it.

**Comment by lucaboesch** [comment]
@grabs I think you just have first to change the default branch of your GitHub repository to something else than master.
Then, you can delete it.

**Comment by grabs** [comment]
@lucaboesch I know, but I don't have the permissions :(.

**Comment by zweitbyte** [comment]
@grabs @lucaboesch
- Set 'main' as the default branch. 
- Set @grabs as Maintainer :-)

**Pull request closed without merging**
