### PR TITLE
Drop german language pack in favour of AMOS

### PR DESCRIPTION
**Pull request by abias**
Hi,

I dropped the german language pack so that the plugin can be translated in AMOS and would like to ask you to pull the commit and publish the new version in the Moodle plugin repo. 

The german translation (for the whole language pack and based on the improved english language pack from https://github.com/moodlehu/moodle-mod_etherpadlite/pull/18) is already submitted in AMOS and should be available within the next days as soon as the lang pack maintainers have checked the contribution.

Thanks,
Alex

### CODE REVIEW

**Comment by abias** [comment]
Update: AMOS translation was already accepted by Ralf Krause and will override from now on the german language pack which is delivered with the plugin

**Comment by goldquest** [comment]
Oh ok, did you submit it to AMOS? 
- Who approves changes? 
- How can I add new Strings, if I add new english ones? (Does it fall back to the included language pack?)
- Does every user, who updates this module, also has to update his AMOS language pack, when a new string is introduced?

I think we should've discussed this, before switching to AMOS.

**Comment by abias** [comment]
Hi Timo,

> Oh ok, did you submit it to AMOS?

Yes, I did that before submitting the pull request. But in fact, everyone could have submitted it.

> Who approves changes?

Ralf Hilgenstock and Ralf Krause, the german language pack maintainers (See https://lang.moodle.org/local/amos/credits.php#credits-language-de)

It normally takes few hours to few days for them to approve contributed translations.

> How can I add new Strings, if I add new english ones? (Does it fall back to the included language pack?)
> Does every user, who updates this module, also has to update his AMOS language pack, when a new string is introduced?

You, as the plugin developer, are in control of the english strings. You upload your plugin with the en language pack to the Moodle plugins repo where the en strings become the base for the translations in AMOS. There's no need to add more than the en language pack to your plugin anymore.

If you add new en strings to your plugin or update existing en strings and upload the new version to the plugin repo, the strings can be instantly translated / updated in AMOS. 

As the plugin developer, you don't need to do more than to take care of the en language pack. If you want to maintain also a non-en language for your plugin, you can do this in AMOS without problems. Other Moodle users can translate your plugin to other languages and they will have to take care of the translation of string additions / updates.

If you add new english strings to your plugin and these strings have not been translated in AMOS, Moodle will fall back to the english strings when they are needed for displaying in Moodle.
If you change a english string in your plugin and a translation does not get translated instantly in AMOS, Moodle will show the outdated translation.

Moodle sites get the plugin translations together with the Moodle core language pack. This is done automatically and a admin doesn't have to do more than installing a language pack.
In recent versions (2.9?) there is also a cron job which updates the installed language pack automatically so that new translations get distributed to Moodle sites quite quickly. 

> I think we should've discussed this, before switching to AMOS.

Well, the plugin has already switched to AMOS. As David Mudrák once told me, translations from AMOS override translations from language pack which are shipped with a plugin. Therefore, Moodle now shows the strings from AMOS and the strings shipped with your plugin are obsolete.

This might seem frightening to you as a plugin developer, but the other side of the medal is that anyone in the Moodle community can translate your plugin without bugging you to include the language pack into your distribution or to adopt every single updated translation. I hope you see the positive side of AMOS now :)

If you have further questions, please let me know.

Thanks,
Alex

**Comment by goldquest** [comment]
Thank you very much for the detailed informations.
I also spoke with others at our department and am feeling better about this now ;)

I wanted to maintain the english and german strings, because this plugin is maintained by a german university. So when I introduce a new english string, I always have to include a german, anyhow.

AMOS complicates this process now for me. I have to wait, till it is approved and also have to update the language pack additionally to updating the plugin.
Also the german language pack maintainer can't always know, if a translation is good or not, because the context is missing.

But I think it is good, that the plugin is now on AMOS, so that people can translate it to other languages. However, I think I will keep my german plugin strings as a fallback and recommendation.

**Pull request merged**
